name: Continous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    audit:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up GO
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.1
            
            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build -v ./...

            - name: Run go vet
              run: go vet ./...

            - name: Install Staticchecks
              run: go install honnef.co/go/tools/cmd/staticcheck@latest
            
            - name: Run staticcheck
              run: staticcheck ./...

            - name: Run race condition tests
              run: go test -race ./...